### ISSUE TITLE
System.Net.WebException: The operation has timed out

### ISSUE THREAD

**Issue by simgreci** [simgreci/SQLXEtoEventHub#14]
When running the sqlclr stored procedure from inside SQLServer:

```
Msg 6522, Level 16, State 1, Procedure sp_send_xe_to_eventhub, Line 0
A .NET Framework error occurred during execution of user-defined routine or aggregate "sp_send_xe_to_eventhub": 
System.Net.WebException: The operation has timed out
System.Net.WebException: 
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at xetohub.core.eventhub.Publisher.PushToEventHub(String sbNamespace, String eventHubName, String policyName, String sasKey, TimeSpan duration, Byte[] payload)
   at xetohub.core.eventhub.Publisher.PushToEventHub(String sbNamespace, String eventHubName, String policyName, String sasKey, TimeSpan duration, String content)
   at xetohub.core.EventHubWriter.Send(String text)
   at xetohub.core.EventHubWriter.Send(XEPayload payload)
   at xetohub.sql.storedprocedures.sp_send_xe_to_eventhub(String trace_name, String event_hub_name, String service_bus_namespace, String policy, String policy_key)
```

**Comment by MindFlavor** [comment]
Fixed in [https://github.com/simgreci/xetohub/commit/b2cc0754e56483707901fe46e0688b59e5359e86](https://github.com/simgreci/xetohub/commit/b2cc0754e56483707901fe46e0688b59e5359e86).
